create table acgc_fossil ("Index" int primary key, Selected int, Name varchar(255))

insert into acgc_fossil values(1, 0, 'Tricera Skull')
insert into acgc_fossil values(2, 0, 'Tricera Torso')
insert into acgc_fossil values(3, 0, 'Tricera Tail')
insert into acgc_fossil values(4, 0, 'T-rex Skull')
insert into acgc_fossil values(5, 0, 'T-rex Torso')
insert into acgc_fossil values(6, 0, 'T-rex Tail')
insert into acgc_fossil values(7, 0, 'Apato Skull')
insert into acgc_fossil values(8, 0, 'Apato Torso')
insert into acgc_fossil values(9, 0, 'Apato Tail')
insert into acgc_fossil values(10, 0, 'Stego Skull')
insert into acgc_fossil values(11, 0, 'Stego Torso')
insert into acgc_fossil values(12, 0, 'Stego Tail')
insert into acgc_fossil values(13, 0, 'Ptera Skull')
insert into acgc_fossil values(14, 0, 'Ptera Left Wing')
insert into acgc_fossil values(15, 0, 'Ptera Right Wing')
insert into acgc_fossil values(16, 0, 'Plesio Skull')
insert into acgc_fossil values(17, 0, 'Plesio Neck')
insert into acgc_fossil values(18, 0, 'Plesio Torso')
insert into acgc_fossil values(19, 0, 'Mammoth Skull')
insert into acgc_fossil values(20, 0, 'Mammoth Torso')
insert into acgc_fossil values(21, 0, 'Amber')
insert into acgc_fossil values(22, 0, 'Dinosaur Track')
insert into acgc_fossil values(23, 0, 'Ammonite')
insert into acgc_fossil values(24, 0, 'Dinosaur Egg')
insert into acgc_fossil values(25, 0, 'Trilobite')
