

create table acgc_umbrella ("Index" int primary key, Selected int, Name varchar(255), "From" varchar(31))

insert into acgc_umbrella values(1, 0, 'Gelato Umbrella', 'store') 
insert into acgc_umbrella values(2, 0, 'Daffodil Parasol', 'store') 
insert into acgc_umbrella values(3, 0, 'Berry Umbrella', 'store') 
insert into acgc_umbrella values(4, 0, 'Orange Umbrella', 'store') 
insert into acgc_umbrella values(5, 0, 'Mod Umbrella', 'store') 
insert into acgc_umbrella values(6, 0, 'Petal Parasol', 'store') 
insert into acgc_umbrella values(7, 0, 'Ribbon Umbrella', 'store') 
insert into acgc_umbrella values(8, 0, 'Gingham Parasol', 'store') 
insert into acgc_umbrella values(9, 0, 'Plaid Parasol', 'store') 
insert into acgc_umbrella values(10, 0, 'Lacy Parasol', 'store') 
insert into acgc_umbrella values(11, 0, 'Elegant Umbrella', 'store') 
insert into acgc_umbrella values(12, 0, 'Dainty Parasol', 'store') 
insert into acgc_umbrella values(13, 0, 'Classic Umbrella', 'store') 
insert into acgc_umbrella values(14, 0, 'Nintendo Parasol', 'store') 
insert into acgc_umbrella values(15, 0, 'Bumbershoot', 'store') 
insert into acgc_umbrella values(16, 0, 'Sunny Parasol', 'store') 
insert into acgc_umbrella values(17, 0, 'Batbrella', 'store') 
insert into acgc_umbrella values(18, 0, 'Checked Umbrella', 'store') 
insert into acgc_umbrella values(19, 0, 'Yellow Umbrella', 'store') 
insert into acgc_umbrella values(20, 0, 'Leaf Umbrella', 'store') 
insert into acgc_umbrella values(21, 0, 'Lotus Parasol', 'store') 
insert into acgc_umbrella values(22, 0, 'Paper Parasol', 'store') 
insert into acgc_umbrella values(23, 0, 'Polka Parasol', 'store') 
insert into acgc_umbrella values(24, 0, 'Sharp Umbrella', 'store') 
insert into acgc_umbrella values(25, 0, 'Twig Parasol', 'store') 
insert into acgc_umbrella values(26, 0, 'Noodle Parasol', 'store') 
insert into acgc_umbrella values(27, 0, 'Hypno Parasol', 'store') 
insert into acgc_umbrella values(28, 0, 'Pastel Parasol', 'store') 
insert into acgc_umbrella values(29, 0, 'Retro Umbrella', 'store') 
insert into acgc_umbrella values(30, 0, 'Icy Umbrella', 'store') 
insert into acgc_umbrella values(31, 0, 'Blue Umbrella', 'store') 
insert into acgc_umbrella values(32, 0, 'Flame Umbrella', 'store') 
insert into acgc_umbrella values(33, 0, 'Bluebell Fan', 'August Fireworks') 
insert into acgc_umbrella values(34, 0, 'Plum Fan', 'August Fireworks') 
insert into acgc_umbrella values(35, 0, 'Bamboo Fan', 'August Fireworks') 
insert into acgc_umbrella values(36, 0, 'Cloud Fan', 'August Fireworks') 
insert into acgc_umbrella values(37, 0, 'Maple Fan', 'August Fireworks') 
insert into acgc_umbrella values(38, 0, 'Fan Fan', 'August Fireworks') 
insert into acgc_umbrella values(39, 0, 'Flower Fan', 'August Fireworks') 
insert into acgc_umbrella values(40, 0, 'Leaf Fan', 'August Fireworks') 
insert into acgc_umbrella values(41, 0, 'Yellow Pinwheel', 'August Fireworks or Grab Bag') 
insert into acgc_umbrella values(42, 0, 'Red Pinwheel', 'August Fireworks or Grab Bag') 
insert into acgc_umbrella values(43, 0, 'Tiger Pinwheel', 'August Fireworks or Grab Bag') 
insert into acgc_umbrella values(44, 0, 'Green Pinwheel', 'August Fireworks or Grab Bag') 
insert into acgc_umbrella values(45, 0, 'Pink Pinwheel', 'August Fireworks or Grab Bag') 
insert into acgc_umbrella values(46, 0, 'Striped Pinwheel', 'August Fireworks or Grab Bag') 
insert into acgc_umbrella values(47, 0, 'Flower Pinwheel', 'August Fireworks or Grab Bag') 
insert into acgc_umbrella values(48, 0, 'Fancy Pinwheel', 'August Fireworks or Grab Bag') 
insert into acgc_umbrella values(49, 0, 'Red Balloon', 'August Fireworks or Sale') 
insert into acgc_umbrella values(50, 0, 'Yellow Balloon', 'August Fireworks') 
insert into acgc_umbrella values(51, 0, 'Blue Balloon', 'August Fireworks or Sale') 
insert into acgc_umbrella values(52, 0, 'Green Balloon', 'August Fireworks') 
insert into acgc_umbrella values(53, 0, 'Purple Balloon', 'August Fireworks') 
insert into acgc_umbrella values(54, 0, 'Bunny P. Balloon', 'August Fireworks') 
insert into acgc_umbrella values(55, 0, 'Bunny B. Balloon', 'August Fireworks') 
insert into acgc_umbrella values(56, 0, 'Bunny O. Balloon', 'August Fireworks') 
