create table acgc_wallpaper ("Index" int primary key, Selected int, Name varchar(255), Status varchar(31), "From" varchar(31))

insert into acgc_wallpaper values(1, 0, 'Chic Wall', 'orderable', 'Grp A') 
insert into acgc_wallpaper values(2, 0, 'Classic Wall', 'orderable', 'Grp B') 
insert into acgc_wallpaper values(3, 0, 'Parlor Wall', 'orderable', 'Grp C') 
insert into acgc_wallpaper values(4, 0, 'Stone Wall', 'orderable', 'Grp A') 
insert into acgc_wallpaper values(5, 0, 'Blue-Trim Wall', 'orderable', 'Grp B') 
insert into acgc_wallpaper values(6, 0, 'Plaster Wall', 'orderable', 'Grp C') 
insert into acgc_wallpaper values(7, 0, 'Classroom Wall', 'unorderable', 'Wendell') 
insert into acgc_wallpaper values(8, 0, 'Lovely Wall', 'orderable', 'Grp A') 
insert into acgc_wallpaper values(9, 0, 'Exotic Wall', 'orderable', 'Grp B') 
insert into acgc_wallpaper values(10, 0, 'Mortar Wall', 'unorderable', 'Wendell') 
insert into acgc_wallpaper values(11, 0, 'Gold Screen Wall', 'orderable', 'Grp C') 
insert into acgc_wallpaper values(12, 0, 'Tea Room Wall', 'orderable', 'Grp A') 
insert into acgc_wallpaper values(13, 0, 'Citrus Wall', 'orderable', 'Grp C') 
insert into acgc_wallpaper values(14, 0, 'Cabin Wall', 'orderable', 'Grp A') 
insert into acgc_wallpaper values(15, 0, 'Blue Tarp', 'unorderable', 'Wendell') 
insert into acgc_wallpaper values(16, 0, 'Lunar Horizon', 'unorderable', 'Wendell') 
insert into acgc_wallpaper values(17, 0, 'Garden Wall', 'unorderable', 'Wendell') 
insert into acgc_wallpaper values(18, 0, 'Spooky Wall', 'unorderable', 'Jack') 
insert into acgc_wallpaper values(19, 0, 'Public Bath Wall', 'unorderable', 'Wendell') 
insert into acgc_wallpaper values(20, 0, 'Green Wall', 'orderable', 'Grp A') 
insert into acgc_wallpaper values(21, 0, 'Blue Wall', 'orderable', 'Grp B') 
insert into acgc_wallpaper values(22, 0, 'Regal Wall', 'orderable', 'Grp C') 
insert into acgc_wallpaper values(23, 0, 'Ranch Wall', 'orderable', 'Grp A') 
insert into acgc_wallpaper values(24, 0, 'Modern Wall', 'orderable', 'Grp B') 
insert into acgc_wallpaper values(25, 0, 'Cabana Wall', 'orderable', 'Grp C') 
insert into acgc_wallpaper values(26, 0, 'Snowman Wall', 'unorderable', 'Snowman') 
insert into acgc_wallpaper values(27, 0, 'Ragged Wall', 'orderable', 'Grp A') 
insert into acgc_wallpaper values(28, 0, 'Music Room Wall', 'unorderable', 'Wendell') 
insert into acgc_wallpaper values(29, 0, 'Plaza Wall', 'orderable', 'Grp A') 
insert into acgc_wallpaper values(30, 0, 'Lattice Wall', 'orderable', 'Grp B') 
insert into acgc_wallpaper values(31, 0, 'Ornate Wall', 'orderable', 'Grp C') 
insert into acgc_wallpaper values(32, 0, 'Modern Screen', 'orderable', 'Grp C') 
insert into acgc_wallpaper values(33, 0, 'Bamboo Wall', 'orderable', 'Grp A') 
insert into acgc_wallpaper values(34, 0, 'Kitchen Wall', 'orderable', 'Grp B') 
insert into acgc_wallpaper values(35, 0, 'Old Brick Wall', 'orderable', 'Grp B') 
insert into acgc_wallpaper values(36, 0, 'Stately Wall', 'orderable', 'Grp C') 
insert into acgc_wallpaper values(37, 0, 'Imperial Wall', 'orderable', 'Grp A') 
insert into acgc_wallpaper values(38, 0, 'Manor Wall', 'orderable', 'Grp B') 
insert into acgc_wallpaper values(39, 0, 'Ivy Wall', 'orderable', 'Grp C') 
insert into acgc_wallpaper values(40, 0, 'Mod Wall', 'orderable', 'Grp A') 
insert into acgc_wallpaper values(41, 0, 'Rose Wall', 'orderable', 'Grp B') 
insert into acgc_wallpaper values(42, 0, 'Wood Paneling', 'orderable', 'Grp C') 
insert into acgc_wallpaper values(43, 0, 'Concrete Wall', 'orderable', 'Grp A') 
insert into acgc_wallpaper values(44, 0, 'Office Wall', 'unorderable', 'Wendell') 
insert into acgc_wallpaper values(45, 0, 'Ancient Wall', 'unorderable', 'Wendell') 
insert into acgc_wallpaper values(46, 0, 'Exquisite Wall', 'orderable', 'Grp C') 
insert into acgc_wallpaper values(47, 0, 'Sandlot Wall', 'unorderable', 'Wendell') 
insert into acgc_wallpaper values(48, 0, 'Jingle Wall', 'unorderable', 'Jingle') 
insert into acgc_wallpaper values(49, 0, 'Meadow Vista', 'unorderable', 'Wendell') 
insert into acgc_wallpaper values(50, 0, 'Tree-Lined Wall', 'unorderable', 'Wendell') 
insert into acgc_wallpaper values(51, 0, 'Mosaic Wall', 'orderable', 'Grp B') 
insert into acgc_wallpaper values(52, 0, 'Arched Window', 'orderable', 'Grp C') 
insert into acgc_wallpaper values(53, 0, 'Basement Wall', 'unorderable', 'Wendell') 
insert into acgc_wallpaper values(54, 0, 'Backgammon Wall', 'unorderable', 'Wendell') 
insert into acgc_wallpaper values(55, 0, 'Kiddie Wall', 'orderable', 'Grp B') 
insert into acgc_wallpaper values(56, 0, 'Shanty Wall', 'orderable', 'Grp C') 
insert into acgc_wallpaper values(57, 0, 'Industrial Wall', 'unorderable', 'Wendell') 
insert into acgc_wallpaper values(58, 0, 'Desert Vista', 'unorderable', 'Wendell') 
insert into acgc_wallpaper values(59, 0, 'Library Wall', 'orderable', 'Grp C') 
insert into acgc_wallpaper values(60, 0, 'Floral Wall', 'orderable', 'Grp A') 
insert into acgc_wallpaper values(61, 0, 'Tropical Vista', 'unorderable', 'Wendell') 
insert into acgc_wallpaper values(62, 0, 'Playroom Wall', 'orderable', 'Grp C') 
insert into acgc_wallpaper values(63, 0, 'Kitschy Wall', 'orderable', 'Grp C') 
insert into acgc_wallpaper values(64, 0, 'Groovy Wall', 'orderable', 'Grp B') 